version: '3.8'

services:
  frontend:
    build: ./front
    ports:
      - "5173:5173"
    volumes:
      - .:/app
      - ./front:/app
      - /app/node_modules
    command: yarn dev --host
    depends_on:
      - backend

  backend:
    build: ./api
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: postgres://postgres:postgres@db:5432/postgres
    depends_on:
      - db

  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgres_data:

